---
abstract: 'Convert between latitude/longitude and GeoHex code (version 2:world wide)'
author:
  - 'OHTSUKA Ko-hei <nene@kokogiko.net>'
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Geo-Hex
provides:
  Geo::Hex:
    file: lib/Geo/Hex.pm
    version: v0.0.2
  Geo::Hex1:
    file: lib/Geo/Hex1.pm
    version: v0.0.2
requires:
  Exporter: 0
  Geo::Proj4: 0
  Math::Round: 0
  Math::Trig: 0
  POSIX: 0
  Test::Base: 0
  version: 0
resources:
  license: http://dev.perl.org/licenses/
version: v0.0.2
